server:
  port: 8080

spring:
  profiles:
    active: local

  datasource:
    hikari:
      maximum-pool-size: 5

  task:
    scheduling:
      pool:
        size: 10

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jasypt:
  encryptor:
    bean: jasyptEncryptor
    password: ${ENCRYPT_KEY}

cookie:
  max-age: ENC(LZMhucgSTnZxWG8aPhgclw==)

jwt:
  secret: ENC(Tnm4CPIFdSiqmH67nWcDfRgaKmpSr4EvRJYZAYLiwOXazIY9aZnLBMlxQnKC2C0j10l6zkOEbRMKIa2W4u7DtIRjCC7QEzCSCdtm1NCEntKRybirDvUH8g==)
  access-token-expiration-period: ENC(46U7S/gH1lH6kpaOwhVaow==)
  refresh-token-expiration-period: ENC(kb9YVXMB9HqUuxoxcnMHXw==)

redis:
  expiration-period: ENC(wFlCe4YyS4e4YGsFGvYAkA==)

mail:
  host: ENC(2PviuayFL6dKe91WydIBx81bpSBoI3FU)
  username: ENC(Hj0Qwzuifugz4sfvDCq9H0u7+WZC4nL+)
  password: ENC(WmCiOlJl61IIAfUIuIkWgKjXEE1GLIL5)
  sender:
    email: ENC(Pv5Gvm0N7LAl4wx51TrKXrkDENW2VIvpW4Ae3ZIod+I=)
    name: ENC(mCgRGGxEhhOBxoVnSOrbJxKMEWBjrDLd)

oauth2:
  properties:
    kakao:
      client-id: dea66bed3e385ce5f8f4f7e817cd5f17
      redirect-uri: http://localhost:8080/oauth
      token-uri: https://kauth.kakao.com/oauth/token?
      user-info-uri: https://kapi.kakao.com/v2/user/me
      member-info-key-word-request:
        email-key-word: kakao_account.email
        nickname-key-word: kakao_account.profile.nickname

    google:
      client-id: 894937970075-tkfknm38alogkb114q8cnid780va7bcf.apps.googleusercontent.com
      client-secret: ENC(qrynytuO78QS+YT7qc1m3gnpafeOsfTcjY25bbd5+YPjm1xVzsgatIEFvzfRJCer)
      redirect-uri: http://localhost:8080/auth/google/callback
      token-uri: https://oauth2.googleapis.com/token?
      user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
      member-info-key-word-request:
        email-key-word: email
        nickname-key-word: name

management:
  server:
    port: 8088
  endpoints:
    web:
      exposure:
        include: prometheus, health
