server:
  port: 8080

spring:
  profiles:
    active: local

  datasource:
    hikari:
      maximum-pool-size: 5

  task:
    scheduling:
      pool:
        size: 10

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jasypt:
  encryptor:
    bean: jasyptEncryptor
    password: ${ENCRYPT_KEY}

cookie:
  max-age: ENC(LZMhucgSTnZxWG8aPhgclw==)

jwt:
  secret: ENC(Tnm4CPIFdSiqmH67nWcDfRgaKmpSr4EvRJYZAYLiwOXazIY9aZnLBMlxQnKC2C0j10l6zkOEbRMKIa2W4u7DtIRjCC7QEzCSCdtm1NCEntKRybirDvUH8g==)
  access-token-expiration-period: ENC(46U7S/gH1lH6kpaOwhVaow==)
  refresh-token-expiration-period: ENC(kb9YVXMB9HqUuxoxcnMHXw==)

redis:
  expiration-period: ENC(wFlCe4YyS4e4YGsFGvYAkA==)

firebase:
  type: ENC(F4zcX8BfVuQNp22k7JJgKV1rtn6SD+6B)
  project_id: ENC(UFaUsDkslrYYTsghWmsZ7Yaxxeavv6UA)
  private_key_id: ENC(CB4BAR9Nn7qymqGMHuDeDAGoUDXgu7d9w7CyDSzdyaiIHVdKs8avawFW3X8xjs8m+fSEz4oS+es=)
  private_key: ENC(QaXAP0NLQ2MQrtmCwTgnv4nOuZn8mrTC7iRCop15+I/ghNnN5N5VOqNO2MZC2OirCixNypfrF62NGmBcU1A66+XN8kgK7ih6BQSchbTCYaWkY7CuFsIN8vYZsXqcoAM2B20x3JqvSiUogCkioeicYEzwfO8XGBOmjzrlG49Xzc/3qd29w3ML+fTazBKyeFL2kTfUwL1rfS/ZjpbdUbYAn6+JW3gU7M9Rm6pTLLq5IUrTcSWJT4Iy1yyrbPC3rKs+ECeiQSKGvUV7zPM4Rd3NqelYmtD70zcgUnUqi8ZpACRUPHd58+AXWdLxXvDlnfPsxkOcDYlVvDdby+0GoEEpmOmbWcOdTA2nBEKY6b7lyv+qLa2aw3gIGEVEwtOE8nBnv46Qfl4/dSH7mqLRharNnInwjEGzKUKpvn/WDEmaMLi9I2crgRsdRNwqEVVKTo59hVSYZCgiHerC2nzgvh6gr0qZBvz1v6+g74efcmH4likOV410yFKSVy+SMaDTilmIwnrJkWg2QunlwUFUARwkAlkvwuE3ouz2RcBop8L/GC/zfvU3zq5ropQa7vbfgzlIss1Z9WMdrXiVqMs36GC2DE9y+Zjkbo1yzCa0G2VIYFN25xPwVAnhBOMrRi9bABIf/gH8thjFC4Pod8VqzVRJH5owM+4x7snXIgmfVibnCQDl3GzIGHMbTvjCsjoAmKnPrAXt1Sj0B5VCwWF1vAGgaPmNUrL60k6jjHBV0cre2fmjtYh3PRRldeLvj5FDfe3poZkIDsdiao/4qT4viRrFMosHCiawphPW/5nlgVLZEv9e4DkJEqiHHPQ9+h6bD715MqBfrc2PgXilbPP1CP6+kustG/xRkctTvusZ4r5Dy4wluhfpWnDbF5Rhs+nePAvcCMAIutm61itXhTp92SX+XROhx0rD1PqXI5YDi97GaoiX+RvXJwt+MuHu+d/otmIAlLjMNjeq4X143EwVt/ivL2KS0qyMpENDPZWmlxJidKDg9TMDG4R0LIs4cd5BxRtX6BQPjsO722XRNAQMfmX+qB3DMQ5GQ/keNzyQiCwZPDYYFs18Eg1mPa47s0YwimXY3barmI/gDNkhbhPrwpAtq5DVoNAYec3IBhuoUWup4U7j53TtuOzvjDW1uu7ZsfoFM88AaZXaZ2hTzRI51AUWaZzO32YS87HkK2HB1gOXQNaKcTx8u0NQtHsQ43bdRnL4FIaVZJPoHv5/BrLJUWt9tXSbynjQW+rXGlAwX2xUoP117e7ma9UWxSCd7UQbmP2kyaaChOK4kDRkoWCfwETX+LuZ3mw8aojgyGH39sktODP8NtmvCVldLubhOBPNCJneZSwMhaxld95ocMPfenXgSMkmPZ8Bjr2eAjYtWERd2sh0GAzsFNy6Js99lLox0cSawMiqBJNuQ+xMGZSVa7GKqRCWp/3fzQG2J9Mr62p4fj0PjO7PLW3bTedtD5YNnEdlt9dA5XoDLx7qu1/bTXR1DPTDxVfbyL+hK6ujJ0IKdBRw81NKaCDAfn6gkrk/SMkLvGJQolcQUJmjs15cIAjXWJfBwDu26sLYWE0NHCaJRQarSiwUkCXhC+HWix4wbU4imX28KY25+wi4lKtKFZ/IS0QJVj4d6IL5nwGcEDxZOCo02lTvKcoXWiOhlS6ZhU5iLQRhqE8BrEI5Z5Zz4ycf1sIsvowYWUt+ZPZFkyIloGjeSqU/iSEiQ7KIhR9OjK/vZ07kr7CrMXJuCHhTWca8VYtFKrQMaJelWdB3/HG+PGTVFshij0S66B6MAeTAEtgfzDWCIzkpCBp59R1XAbK4bVR4G9n8lmlKLFmEmj60HBTHkBoaR15ThlTp1cqABXjnQGGI3gj+EB+RmDD+TnYgEaqTXWbLR1evZlalxlVH4MhB3iCVnL+jFyaPdeKAT0od2Vk3dYAbxRDWFxC8dEjEk3vuuL6vPDyTNoDRDrZDwyWFdn90eQdg/y5ighiHY9dQhjziQbwnpzCj6fXVMRo+5XoTr6vwof6Ftv+9Fis0jct/IW9QDN8DeljqaQGeb+B10IbUkcJOs/BIzoeszcY7CL3aXUIRDi+IXn6Pmo7jF+x4XKeEMmKU9I9awmGiZdVGVSrSfv+z4OhhD7ZoicVAWPoxSkhvCi3UIbrcWo4+nR1T8qf37G4azIHzmkJwGvi4LB3/V54Pw8nEYBrYsKGQ/nh8AAxOZKVQLPVgMsBjU8z2IVKElMbZwlvAj5SbGjtBdRK3+I/gAVzXuBcp8xXqgg45woBywvFc1jjnmm72UXc27VkN6PoKr54XqCnsL/bP3JSHRUbWK6f+kErsQZePww==)
  client_email: ENC(+j6daXlFgOM38ayzSuJy0Q2vHVq/eO94eEyGOr+e0ggyap3J5LOVLmb+riSegU0SFYQNRDF24mX82JHUrigb2vkvXc30vEnm)
  client_id: ENC(RTaiQPN2N0P7j+SD3V50kVOKW7rYQLddlZHgVWYykmQ=)
  auth_uri: ENC(pMLc1oq5YZyyA9U0QZFOIALtiLg835Y4rBVdTPGy9U8cH/b/h336fQyzVXTyUpQlFIzka7svAbM=)
  token_uri: ENC(MfLebQuWZGWcUdT+zNf7gaAspKQgvdWtcFSaTaGD7D1xRQHI736TeoQNgg43ykIM)
  auth_provider_x509_cert_url: ENC(0Rjf2AbMiB9aCYNMSxlUsp91hfJRcPg+A0BVKLfPsVuhjKCwoMowgUGwsz2nsZphzF43BCA3+VY=)
  client_x509_cert_url: ENC(qmWXGlIex60ylnfTgJmw+jUQqh3yRWdX7comN5XWwfxByHXLhQAZP/kPi7+Sb6A/buxb9DGH3daqvZPDM8lKiz5yGFHKvtgwIEnStc7LzUSTOeXAJv/kwdG7sckrUokeYpzVtJKL1CQBB9YtiZs0QBc9Z1bVJeBO)
  universe_domain: ENC(Q4ZkcZWMOXTfgk7OODq/M7utCcr1tIsN)

mail:
  host: ENC(2PviuayFL6dKe91WydIBx81bpSBoI3FU)
  username: ENC(Hj0Qwzuifugz4sfvDCq9H0u7+WZC4nL+)
  password: ENC(WmCiOlJl61IIAfUIuIkWgKjXEE1GLIL5)
  sender:
    email: ENC(Pv5Gvm0N7LAl4wx51TrKXrkDENW2VIvpW4Ae3ZIod+I=)
    name: ENC(mCgRGGxEhhOBxoVnSOrbJxKMEWBjrDLd)

oauth2:
  properties:
    kakao:
      client-id: dea66bed3e385ce5f8f4f7e817cd5f17
      redirect-uri: http://localhost:8080/oauth
      token-uri: https://kauth.kakao.com/oauth/token?
      user-info-uri: https://kapi.kakao.com/v2/user/me
      member-info-key-word-request:
        email-key-word: kakao_account.email
        nickname-key-word: kakao_account.profile.nickname

    google:
      client-id: 894937970075-tkfknm38alogkb114q8cnid780va7bcf.apps.googleusercontent.com
      client-secret: ENC(qrynytuO78QS+YT7qc1m3gnpafeOsfTcjY25bbd5+YPjm1xVzsgatIEFvzfRJCer)
      redirect-uri: http://localhost:8080/auth/google/callback
      token-uri: https://oauth2.googleapis.com/token?
      user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
      member-info-key-word-request:
        email-key-word: email
        nickname-key-word: name

management:
  server:
    port: 8088
  endpoints:
    web:
      exposure:
        include: prometheus, health
