spring:
  datasource:
    url: ENC(uLIb+jZ41BRTbVHWhJKGP8inZwh5S4lDmVrzmJoP4sMMsoLtuX7vO0cgme/yx9W7z1HMk0+YmDyBkGbUf3/KNR15oA+PwCjIPehLp4xXyVVp7iw1iaYy+slTsyCshAW24PCIybrCBc7CIXPdC6acCT2MO9P527Y+mvFaiVIgE4eDcbFrfekiyuXzepQwCL24ZqwNxPS52CY=)
    username: ENC(1hd/ZiyIhjBoiBhs87SnpQ==)
    password: ENC(XKEsYiCiOgXrQX/gwiGUTUOU+rfD8TyU)
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: false
    baseline-on-migrate: false

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
        show_sql: true

schedule:
  enable: true
  mail: true

file:
  upload:
    location: ENC(sC+qXiI6EobSpCEDLmoWyCUiV+b8eJiJxOsQIyGP/9mopq8ZAlbGHg==)
