spring:
  datasource:
    url: ENC(L9rONQFAg6+N9qfyk+WS8BPMNr9GqS8NlVU6nD5ru+6sp0BihhSFDPv5oBwxdPovt0cKAsEy1ss12k14HlRxSgb2FYYGCG942BYDE1rawwCXUYFShXKajwn04KfgAd2nDfoqQv/LbPMtiV0xS1DPr8J/KiHifZ7pAfqAqGX10k2F5L3iEiWcYf8n6eFKZVt2NlLZyenupcM=)
    username: ENC(bgdntWNvrp9NPrUb2qT0CQ==)
    password: ENC(bgdntWNvrp9NPrUb2qT0CQ==)
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: false
    baseline-on-migrate: false

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
        show_sql: true

schedule:
  enable: true
  mail: true

file:
  upload:
    location: ENC(sC+qXiI6EobSpCEDLmoWyCUiV+b8eJiJxOsQIyGP/9mopq8ZAlbGHg==)
