server:
  port: 8080

spring:
  profiles:
    active: local
  datasource:
    hikari:
      maximum-pool-size: 5
  task:
    scheduling:
      pool:
        size: 10
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jasypt:
  encryptor:
    bean: jasyptEncryptor
    password: ${ENCRYPT_KEY}

jwt:
  secret: ENC(Tnm4CPIFdSiqmH67nWcDfRgaKmpSr4EvRJYZAYLiwOXazIY9aZnLBMlxQnKC2C0j10l6zkOEbRMKIa2W4u7DtIRjCC7QEzCSCdtm1NCEntKRybirDvUH8g==)
  expiration-period: ENC(wtkJPr944E3bs6eMwjj4lQ==)

mail:
  host: ENC(2PviuayFL6dKe91WydIBx81bpSBoI3FU)
  username: ENC(Hj0Qwzuifugz4sfvDCq9H0u7+WZC4nL+)
  password: ENC(WmCiOlJl61IIAfUIuIkWgKjXEE1GLIL5)
  sender:
    email: ENC(Pv5Gvm0N7LAl4wx51TrKXrkDENW2VIvpW4Ae3ZIod+I=)
    name: ENC(mCgRGGxEhhOBxoVnSOrbJxKMEWBjrDLd)

oauth2:
  user:
    kakao:
      client-id: dea66bed3e385ce5f8f4f7e817cd5f17
      redirect-uri: http://localhost:8080/oauth
  provider:
    kakao:
      token-uri: https://kauth.kakao.com/oauth/token?
      user-info-uri: https://kapi.kakao.com/v2/user/me
